#!/bin/bash
#
### MONITORS ###
external_monitor=$(xrandr --query | grep 'HDMI1')

if [[ $external_monitor = HDMI1\ connected* ]]; then
  xrandr --output HDMI1 --auto --primary --output eDP1 --off
  bspc monitor HDMI1 -d 1 2 3 4 5 6 7 8 9
else
  xrandr --output eDP1 --auto
  bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9
fi

# BSPWM Configuration
_bc() {
  bspc config "$@"
}

# BSPWM Configuration
_bc window_gap                       8
_bc top_padding                      26
_bc top_monocle_padding              0
_bc border_width                     2
_bc bottom_padding                   0
_bc left_padding                     0
_bc right_padding                    0
_bc single_monocle                   false
_bc click_to_focus                   false
_bc split_ratio                      0.50
_bc borderless_monocle               true
_bc gapless_monocle                  true
_bc focus_by_distance                true
_bc paddingless_monocle              true
_bc focus_follows_pointer            true
_bc ignore_ewmh_focus                true
_bc history_aware_focus              true
_bc remove_disabled_monitors         true
_bc pointer_modifier mod1
_bc pointer_action1 move
_bc pointer_action2 resize_side
_bc pointer_action3 resize_corner

# Colors
rosepine_background="#2e3440"
rosepine_foreground="#d8dee9"
rosepine_accent="#88c0d0"
rosepine_active="#bf616a"
rosepine_focused="#8fbcbb"
rosepine_normal="#4c566a"
_bc normal_border_color "$rosepine_normal"
_bc focused_border_color "$rosepine_focused"
_bc active_border_color "$rosepine_active"

# Rules
bspc rule -a mpv state=tiled
bspc rule -a flameshot state='floating'
bspc rule -a *:SPLASH state=floating
bspc desktop -f 1

# Init-Daemons
command -v sxhkd && sxhkd &
command -v picom && picom &
command -v dunst && dunst &
setxkbmap -option ctrl:nocaps &

# Autostart
command -v feh && ~/.fehbg &
command -v polybar && polybar &
