#!/bin/bash
#
###MONITORS###
bspc monitor -d 1 2 3 4 5 6 7 8 9 

external_monitor=$(xrandr --query | grep 'HDMI1')

if [[ $external_monitor = HDMI1\ connected* ]]; then
  xrandr --output HDMI1 --auto --primary --output eDP1 --off
  bspc monitor HDMI1 -d 1 2 3 4 5 6 7 8 9
else
  xrandr --output eDP1 --auto
  bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9
fi

_bc() {
  bspc config "$@"
}

#### BSPWM configuration ####
_bc window_gap 			  						8
_bc top_padding 									2
_bc top_monocle_padding 					0
_bc border_width 								  2
_bc bottom_padding                0
_bc left_padding                  0
_bc right_padding 								0
_bc single_monocle                false
_bc click_to_focus                false
_bc split_ratio                   0.50
_bc borderless_monocle            true
_bc gapless_monocle               true
_bc focus_by_distance             true
_bc paddingless_monocle  	  			true
_bc focus_follows_pointer         true
_bc ignore_ewmh_focus 		  			true
_bc history_aware_focus           true
_bc remove_disabled_monitors      true
_bc pointer_modifier mod1
_bc pointer_action1 move
_bc pointer_action2 resize_side
_bc pointer_action3 resize_corner

# Colors
bspc config active_border_color "#8aadf4"
bspc config focused_border_color "#ee99a0"
bspc config normal_border_color "#5b6078"
bspc config presel_feedback_color "#a6da95"

# Rules
bspc rule -a Emacs state=tiled
bspc rule -a firefox -o desktop=2
bspc rule -a mpv state=tiled
bspc rule -a flameshot state='floating'
bspc rule -a *:SPLASH state=floating
bspc desktop -f 1

# Init-Daemons
sxhkd &
picom &
dunst &
setxkbmap -option ctrl:nocaps &
xsetroot -cursor_name left_ptr &

# Autostart
~/.fehbg &
~/.config/bspwm/autostart &
